const MOVIE_ROWS_DESKTOP = 3
const MOVIE_ROWS_TABLET = 2
const MOVIE_ROWS_MOBILE = 2
const SHORTS_DURATION = 40
const REGEXP_EMAIL = '[a-zA-Z0-9_.]+@[a-zA-Z0-9_]+\\.[a-z]{2,}'

export {
  MOVIE_ROWS_DESKTOP,
  MOVIE_ROWS_TABLET,
  MOVIE_ROWS_MOBILE,
  SHORTS_DURATION,
  REGEXP_EMAIL,
}